"""add poster_url and tmdb_id to movie

Revision ID: 3078d67b3a77
Revises: 46a9ae4f38eb
Create Date: 2026-10-10 16:09:02.739914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3078d67b3a77'
down_revision = '46a9ae4f38eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
